Feature/repost
lucasmoraismt/projeto-linkr pull request #29
Opened 2021-06-02 20:05 UTC by ptrkc

incorpora as mudanças do branch fix/small-layout-changes

2021-06-02 21:05 UTC, thiagoribb requested changes

2021-06-02 21:05 UTC, thiagoribb commented on src/components/Timeline/RepostButton.js
> +      reload();
Por que recarregar a página e não acrescentar o repost?

2021-06-02 21:19 UTC, ptrkc commented on src/components/Timeline/RepostButton.js
> +      reload();
Eu tinha feito assim inicialmente, assim como fiz com a quantidade de comentários de um post, mas quando tem reposts desse mesmo post na página, o que é bem comum, só o post onde você clicou aparece com +1 repost. Como o request tava voltando bem rápido, achei válido fazer assim.

2021-06-04 14:56 UTC, thiagoribb approved these changes

2021-06-04 14:59 UTC, merged